export const SET_SHOW_PICK_FIELD_ONEWAY = "SET_SHOW_PICK_FIELD_ONEWAY";
export const SET_SHOW_DROP_FIELD_ONEWAY = "SET_SHOW_DROP_FIELD_ONEWAY";
export const SET_SHOW_PICK_FIELD_RETURN = "SET_SHOW_PICK_FIELD_RETURN";
export const SET_SHOW_DROP_FIELD_RETURN = "SET_SHOW_DROP_FIELD_RETURN";

export const RESET_FIELDS = "RESET_FIELDS";
//?modal ifo
export const SET_MODAL_INFO = "SET_MODAL_INFO";
export const SET_WAITING_MODAL_INFO = "SET_WAITING_MODAL_INFO";
export const SET_CRUMBS = "SET_CRUMBS";
